version: "3.9"

services:
  ch6-crypto-m1-pudding:
    build: crypto/ch6_m1_pudding
    ports:
      - "10006:1337"
    environment:
      - PROD=true
      - FLAG=${FLAG_06}
  ch7-crypto-m2-byoh:
    build: crypto/ch7_m2_byoh
    ports:
      - "10007:1337"
    environment:
      - PROD=true
      - FLAG=${FLAG_07}
  ch8-crypto-m3-ezdsa:
    build: crypto/ch8_m3_ezdsa
    ports:
      - "10008:1337"
    environment:
      - PROD=true
      - FLAG=${FLAG_08}
  ch12-web-m1-gif-storage:
    build: web/ch12_m1_gif_storage
    ports:
      - "10012:80"
    environment:
      - FLAG=${FLAG_12}
  ch14-web-m3-xss2sqli:
    build: web/ch14_m3_xss2sqli
    ports:
      - "10014:8000"
    environment:
      - PROD=true
      - SECRET_KEY=${c14_SECRET_KEY}
      - ADMIN_PASSWORD=${c14_ADMIN_PASSWORD}
      - CTF_FLAG=${FLAG_14}
      - CAPTCHA_SITE_KEY=${c14_CAPTCHA_SITE_KEY}
      - CAPTCHA_SECRET_KEY=${c14_CAPTCHA_SECRET_KEY}
  ch19-misc-pyrun:
    build: misc/ch19_pyrun
    runtime: runc
    ports:
      - "10019:1337"
    environment:
      - FLAG=${FLAG_19}
  ch3-pwn-m2-lottery-predictor-game:
    build: pwn/ch3_m2_lottery_predictor_game
    runtime: runc
    ports:
      - "10003:1337"
    environment:
      - FLAG=${FLAG_3}
  ch1-pwn-m1-pwn_bankde_fc:
    build: pwn/ch1_m1_pwn_bankde_fc
    runtime: runc
    ports:
      - "10001:1337"
    environment:
      - FLAG=${FLAG_1}
  ch2-pwn-m3-pwn_super_guesser:
    build: pwn/ch2_m3_super_guesser
    runtime: runc
    ports:
      - "10001:1337"
    environment:
      - FLAG=${FLAG_2}
  ch4-pwn-m4-pwn_super_guesser_v2:
    build: pwn/ch4_m4_super_guesser_v2
    runtime: runc
    ports:
      - "10001:1337"
    environment:
      - FLAG=${FLAG_4}
